package net.minecraft.server;

import com.google.common.collect.Sets;

import net.mcavenue.redspigot.registries.BlockRegistry;

import java.util.Set;
import javax.annotation.Nullable;

import org.springframework.beans.factory.annotation.Autowired;

public class Blocks {

	private Set<Block> dU;
	public Block AIR;
	public Block STONE;
	public BlockGrass GRASS;
	public Block DIRT;
	public Block COBBLESTONE;
	public Block PLANKS;
	public Block SAPLING;
	public Block BEDROCK;
	public BlockFlowing FLOWING_WATER;
	public BlockStationary WATER;
	public BlockFlowing FLOWING_LAVA;
	public BlockStationary LAVA;
	public BlockSand SAND;
	public Block GRAVEL;
	public Block GOLD_ORE;
	public Block IRON_ORE;
	public Block COAL_ORE;
	public Block LOG;
	public Block LOG2;
	public BlockLeaves LEAVES;
	public BlockLeaves LEAVES2;
	public Block SPONGE;
	public Block GLASS;
	public Block LAPIS_ORE;
	public Block LAPIS_BLOCK;
	public Block DISPENSER;
	public Block SANDSTONE;
	public Block NOTEBLOCK;
	public Block BED;
	public Block GOLDEN_RAIL;
	public Block DETECTOR_RAIL;
	public BlockPiston STICKY_PISTON;
	public Block WEB;
	public BlockLongGrass TALLGRASS;
	public BlockDeadBush DEADBUSH;
	public BlockPiston PISTON;
	public BlockPistonExtension PISTON_HEAD;
	public Block WOOL;
	public BlockPistonMoving PISTON_EXTENSION;
	public BlockFlowers YELLOW_FLOWER;
	public BlockFlowers RED_FLOWER;
	public BlockPlant BROWN_MUSHROOM;
	public BlockPlant RED_MUSHROOM;
	public Block GOLD_BLOCK;
	public Block IRON_BLOCK;
	public BlockStepAbstract DOUBLE_STONE_SLAB;
	public BlockStepAbstract STONE_SLAB;
	public Block BRICK_BLOCK;
	public Block TNT;
	public Block BOOKSHELF;
	public Block MOSSY_COBBLESTONE;
	public Block OBSIDIAN;
	public Block TORCH;
	public BlockFire FIRE;
	public Block MOB_SPAWNER;
	public Block OAK_STAIRS;
	public BlockChest CHEST;
	public BlockRedstoneWire REDSTONE_WIRE;
	public Block DIAMOND_ORE;
	public Block DIAMOND_BLOCK;
	public Block CRAFTING_TABLE;
	public Block WHEAT;
	public Block FARMLAND;
	public Block FURNACE;
	public Block LIT_FURNACE;
	public Block STANDING_SIGN;
	public BlockDoor WOODEN_DOOR;
	public BlockDoor SPRUCE_DOOR;
	public BlockDoor BIRCH_DOOR;
	public BlockDoor JUNGLE_DOOR;
	public BlockDoor ACACIA_DOOR;
	public BlockDoor DARK_OAK_DOOR;
	public Block LADDER;
	public Block RAIL;
	public Block STONE_STAIRS;
	public Block WALL_SIGN;
	public Block LEVER;
	public Block STONE_PRESSURE_PLATE;
	public BlockDoor IRON_DOOR;
	public Block WOODEN_PRESSURE_PLATE;
	public Block REDSTONE_ORE;
	public Block LIT_REDSTONE_ORE;
	public Block UNLIT_REDSTONE_TORCH;
	public Block REDSTONE_TORCH;
	public Block STONE_BUTTON;
	public Block SNOW_LAYER;
	public Block ICE;
	public Block SNOW;
	public BlockCactus CACTUS;
	public Block CLAY;
	public BlockReed REEDS;
	public Block JUKEBOX;
	public Block FENCE;
	public Block SPRUCE_FENCE;
	public Block BIRCH_FENCE;
	public Block JUNGLE_FENCE;
	public Block DARK_OAK_FENCE;
	public Block ACACIA_FENCE;
	public Block PUMPKIN;
	public Block NETHERRACK;
	public Block SOUL_SAND;
	public Block GLOWSTONE;
	public BlockPortal PORTAL;
	public Block LIT_PUMPKIN;
	public Block CAKE;
	public BlockRepeater UNPOWERED_REPEATER;
	public BlockRepeater POWERED_REPEATER;
	public Block TRAPDOOR;
	public Block MONSTER_EGG;
	public Block STONEBRICK;
	public Block BROWN_MUSHROOM_BLOCK;
	public Block RED_MUSHROOM_BLOCK;
	public Block IRON_BARS;
	public Block GLASS_PANE;
	public Block MELON_BLOCK;
	public Block PUMPKIN_STEM;
	public Block MELON_STEM;
	public Block VINE;
	public Block FENCE_GATE;
	public Block SPRUCE_FENCE_GATE;
	public Block BIRCH_FENCE_GATE;
	public Block JUNGLE_FENCE_GATE;
	public Block DARK_OAK_FENCE_GATE;
	public Block ACACIA_FENCE_GATE;
	public Block BRICK_STAIRS;
	public Block STONE_BRICK_STAIRS;
	public BlockMycel MYCELIUM;
	public Block WATERLILY;
	public Block NETHER_BRICK;
	public Block NETHER_BRICK_FENCE;
	public Block NETHER_BRICK_STAIRS;
	public Block NETHER_WART;
	public Block ENCHANTING_TABLE;
	public Block BREWING_STAND;
	public BlockCauldron cauldron;
	public Block END_PORTAL;
	public Block END_PORTAL_FRAME;
	public Block END_STONE;
	public Block DRAGON_EGG;
	public Block REDSTONE_LAMP;
	public Block LIT_REDSTONE_LAMP;
	public BlockStepAbstract DOUBLE_WOODEN_SLAB;
	public BlockStepAbstract WOODEN_SLAB;
	public Block COCOA;
	public Block SANDSTONE_STAIRS;
	public Block EMERALD_ORE;
	public Block ENDER_CHEST;
	public BlockTripwireHook TRIPWIRE_HOOK;
	public Block TRIPWIRE;
	public Block EMERALD_BLOCK;
	public Block SPRUCE_STAIRS;
	public Block BIRCH_STAIRS;
	public Block JUNGLE_STAIRS;
	public Block COMMAND_BLOCK;
	public BlockBeacon BEACON;
	public Block COBBLESTONE_WALL;
	public Block FLOWER_POT;
	public Block CARROTS;
	public Block POTATOES;
	public Block WOODEN_BUTTON;
	public BlockSkull SKULL;
	public Block ANVIL;
	public Block TRAPPED_CHEST;
	public Block LIGHT_WEIGHTED_PRESSURE_PLATE;
	public Block HEAVY_WEIGHTED_PRESSURE_PLATE;
	public BlockRedstoneComparator UNPOWERED_COMPARATOR;
	public BlockRedstoneComparator POWERED_COMPARATOR;
	public BlockDaylightDetector DAYLIGHT_DETECTOR;
	public BlockDaylightDetector DAYLIGHT_DETECTOR_INVERTED;
	public Block REDSTONE_BLOCK;
	public Block QUARTZ_ORE;
	public BlockHopper HOPPER;
	public Block QUARTZ_BLOCK;
	public Block QUARTZ_STAIRS;
	public Block ACTIVATOR_RAIL;
	public Block DROPPER;
	public Block STAINED_HARDENED_CLAY;
	public Block BARRIER;
	public Block IRON_TRAPDOOR;
	public Block HAY_BLOCK;
	public Block CARPET;
	public Block HARDENED_CLAY;
	public Block COAL_BLOCK;
	public Block PACKED_ICE;
	public Block ACACIA_STAIRS;
	public Block DARK_OAK_STAIRS;
	public Block SLIME;
	public BlockTallPlant DOUBLE_PLANT;
	public BlockStainedGlass STAINED_GLASS;
	public BlockStainedGlassPane STAINED_GLASS_PANE;
	public Block PRISMARINE;
	public Block SEA_LANTERN;
	public Block STANDING_BANNER;
	public Block WALL_BANNER;
	public Block RED_SANDSTONE;
	public Block RED_SANDSTONE_STAIRS;
	public BlockStepAbstract DOUBLE_STONE_SLAB2;
	public BlockStepAbstract STONE_SLAB2;
	public Block END_ROD;
	public Block CHORUS_PLANT;
	public Block CHORUS_FLOWER;
	public Block PURPUR_BLOCK;
	public Block PURPUR_PILLAR;
	public Block PURPUR_STAIRS;
	public BlockStepAbstract PURPUR_DOUBLE_SLAB;
	public BlockStepAbstract PURPUR_SLAB;
	public Block END_BRICKS;
	public Block BEETROOT;
	public Block GRASS_PATH;
	public Block END_GATEWAY;
	public Block dc;
	public Block dd;
	public Block FROSTED_ICE;
	public Block df;
	public Block dg;
	public Block dh;
	public Block di;
	public Block dj;
	public Block dk;
	public Block WHITE_SHULKER_BOX;
	public Block dm;
	public Block dn;
	public Block LIGHT_BLUE_SHULKER_BOX;
	public Block dp;
	public Block dq;
	public Block dr;
	public Block ds;
	public Block dt;
	public Block du;
	public Block dv;
	public Block dw;
	public Block dx;
	public Block dy;
	public Block dz;
	public Block dA;
	public Block dB;
	public Block dC;
	public Block dD;
	public Block dE;
	public Block dF;
	public Block dG;
	public Block dH;
	public Block dI;
	public Block dJ;
	public Block dK;
	public Block dL;
	public Block dM;
	public Block dN;
	public Block dO;
	public Block dP;
	public Block dQ;
	public Block dR;
	public Block dS;
	public Block STRUCTURE_BLOCK;
	@Autowired
	private BlockRegistry REGISTRY;

	@Nullable
	private Block get(String s) {
		Block block = (Block) REGISTRY.get(new MinecraftKey(s));

		if (!dU.add(block)) {
			throw new IllegalStateException("Invalid Block requested: " + s);
		} else {
			return block;
		}
	}

	{
		dU = Sets.newHashSet();
		AIR = get("air");
		STONE = get("stone");
		GRASS = (BlockGrass) get("grass");
		DIRT = get("dirt");
		COBBLESTONE = get("cobblestone");
		PLANKS = get("planks");
		SAPLING = get("sapling");
		BEDROCK = get("bedrock");
		FLOWING_WATER = (BlockFlowing) get("flowing_water");
		WATER = (BlockStationary) get("water");
		FLOWING_LAVA = (BlockFlowing) get("flowing_lava");
		LAVA = (BlockStationary) get("lava");
		SAND = (BlockSand) get("sand");
		GRAVEL = get("gravel");
		GOLD_ORE = get("gold_ore");
		IRON_ORE = get("iron_ore");
		COAL_ORE = get("coal_ore");
		LOG = get("log");
		LOG2 = get("log2");
		LEAVES = (BlockLeaves) get("leaves");
		LEAVES2 = (BlockLeaves) get("leaves2");
		SPONGE = get("sponge");
		GLASS = get("glass");
		LAPIS_ORE = get("lapis_ore");
		LAPIS_BLOCK = get("lapis_block");
		DISPENSER = get("dispenser");
		SANDSTONE = get("sandstone");
		NOTEBLOCK = get("noteblock");
		BED = get("bed");
		GOLDEN_RAIL = get("golden_rail");
		DETECTOR_RAIL = get("detector_rail");
		STICKY_PISTON = (BlockPiston) get("sticky_piston");
		WEB = get("web");
		TALLGRASS = (BlockLongGrass) get("tallgrass");
		DEADBUSH = (BlockDeadBush) get("deadbush");
		PISTON = (BlockPiston) get("piston");
		PISTON_HEAD = (BlockPistonExtension) get("piston_head");
		WOOL = get("wool");
		PISTON_EXTENSION = (BlockPistonMoving) get("piston_extension");
		YELLOW_FLOWER = (BlockFlowers) get("yellow_flower");
		RED_FLOWER = (BlockFlowers) get("red_flower");
		BROWN_MUSHROOM = (BlockPlant) get("brown_mushroom");
		RED_MUSHROOM = (BlockPlant) get("red_mushroom");
		GOLD_BLOCK = get("gold_block");
		IRON_BLOCK = get("iron_block");
		DOUBLE_STONE_SLAB = (BlockStepAbstract) get("double_stone_slab");
		STONE_SLAB = (BlockStepAbstract) get("stone_slab");
		BRICK_BLOCK = get("brick_block");
		TNT = get("tnt");
		BOOKSHELF = get("bookshelf");
		MOSSY_COBBLESTONE = get("mossy_cobblestone");
		OBSIDIAN = get("obsidian");
		TORCH = get("torch");
		FIRE = (BlockFire) get("fire");
		MOB_SPAWNER = get("mob_spawner");
		OAK_STAIRS = get("oak_stairs");
		CHEST = (BlockChest) get("chest");
		REDSTONE_WIRE = (BlockRedstoneWire) get("redstone_wire");
		DIAMOND_ORE = get("diamond_ore");
		DIAMOND_BLOCK = get("diamond_block");
		CRAFTING_TABLE = get("crafting_table");
		WHEAT = get("wheat");
		FARMLAND = get("farmland");
		FURNACE = get("furnace");
		LIT_FURNACE = get("lit_furnace");
		STANDING_SIGN = get("standing_sign");
		WOODEN_DOOR = (BlockDoor) get("wooden_door");
		SPRUCE_DOOR = (BlockDoor) get("spruce_door");
		BIRCH_DOOR = (BlockDoor) get("birch_door");
		JUNGLE_DOOR = (BlockDoor) get("jungle_door");
		ACACIA_DOOR = (BlockDoor) get("acacia_door");
		DARK_OAK_DOOR = (BlockDoor) get("dark_oak_door");
		LADDER = get("ladder");
		RAIL = get("rail");
		STONE_STAIRS = get("stone_stairs");
		WALL_SIGN = get("wall_sign");
		LEVER = get("lever");
		STONE_PRESSURE_PLATE = get("stone_pressure_plate");
		IRON_DOOR = (BlockDoor) get("iron_door");
		WOODEN_PRESSURE_PLATE = get("wooden_pressure_plate");
		REDSTONE_ORE = get("redstone_ore");
		LIT_REDSTONE_ORE = get("lit_redstone_ore");
		UNLIT_REDSTONE_TORCH = get("unlit_redstone_torch");
		REDSTONE_TORCH = get("redstone_torch");
		STONE_BUTTON = get("stone_button");
		SNOW_LAYER = get("snow_layer");
		ICE = get("ice");
		SNOW = get("snow");
		CACTUS = (BlockCactus) get("cactus");
		CLAY = get("clay");
		REEDS = (BlockReed) get("reeds");
		JUKEBOX = get("jukebox");
		FENCE = get("fence");
		SPRUCE_FENCE = get("spruce_fence");
		BIRCH_FENCE = get("birch_fence");
		JUNGLE_FENCE = get("jungle_fence");
		DARK_OAK_FENCE = get("dark_oak_fence");
		ACACIA_FENCE = get("acacia_fence");
		PUMPKIN = get("pumpkin");
		NETHERRACK = get("netherrack");
		SOUL_SAND = get("soul_sand");
		GLOWSTONE = get("glowstone");
		PORTAL = (BlockPortal) get("portal");
		LIT_PUMPKIN = get("lit_pumpkin");
		CAKE = get("cake");
		UNPOWERED_REPEATER = (BlockRepeater) get("unpowered_repeater");
		POWERED_REPEATER = (BlockRepeater) get("powered_repeater");
		TRAPDOOR = get("trapdoor");
		MONSTER_EGG = get("monster_egg");
		STONEBRICK = get("stonebrick");
		BROWN_MUSHROOM_BLOCK = get("brown_mushroom_block");
		RED_MUSHROOM_BLOCK = get("red_mushroom_block");
		IRON_BARS = get("iron_bars");
		GLASS_PANE = get("glass_pane");
		MELON_BLOCK = get("melon_block");
		PUMPKIN_STEM = get("pumpkin_stem");
		MELON_STEM = get("melon_stem");
		VINE = get("vine");
		FENCE_GATE = get("fence_gate");
		SPRUCE_FENCE_GATE = get("spruce_fence_gate");
		BIRCH_FENCE_GATE = get("birch_fence_gate");
		JUNGLE_FENCE_GATE = get("jungle_fence_gate");
		DARK_OAK_FENCE_GATE = get("dark_oak_fence_gate");
		ACACIA_FENCE_GATE = get("acacia_fence_gate");
		BRICK_STAIRS = get("brick_stairs");
		STONE_BRICK_STAIRS = get("stone_brick_stairs");
		MYCELIUM = (BlockMycel) get("mycelium");
		WATERLILY = get("waterlily");
		NETHER_BRICK = get("nether_brick");
		NETHER_BRICK_FENCE = get("nether_brick_fence");
		NETHER_BRICK_STAIRS = get("nether_brick_stairs");
		NETHER_WART = get("nether_wart");
		ENCHANTING_TABLE = get("enchanting_table");
		BREWING_STAND = get("brewing_stand");
		cauldron = (BlockCauldron) get("cauldron");
		END_PORTAL = get("end_portal");
		END_PORTAL_FRAME = get("end_portal_frame");
		END_STONE = get("end_stone");
		DRAGON_EGG = get("dragon_egg");
		REDSTONE_LAMP = get("redstone_lamp");
		LIT_REDSTONE_LAMP = get("lit_redstone_lamp");
		DOUBLE_WOODEN_SLAB = (BlockStepAbstract) get("double_wooden_slab");
		WOODEN_SLAB = (BlockStepAbstract) get("wooden_slab");
		COCOA = get("cocoa");
		SANDSTONE_STAIRS = get("sandstone_stairs");
		EMERALD_ORE = get("emerald_ore");
		ENDER_CHEST = get("ender_chest");
		TRIPWIRE_HOOK = (BlockTripwireHook) get("tripwire_hook");
		TRIPWIRE = get("tripwire");
		EMERALD_BLOCK = get("emerald_block");
		SPRUCE_STAIRS = get("spruce_stairs");
		BIRCH_STAIRS = get("birch_stairs");
		JUNGLE_STAIRS = get("jungle_stairs");
		COMMAND_BLOCK = get("command_block");
		BEACON = (BlockBeacon) get("beacon");
		COBBLESTONE_WALL = get("cobblestone_wall");
		FLOWER_POT = get("flower_pot");
		CARROTS = get("carrots");
		POTATOES = get("potatoes");
		WOODEN_BUTTON = get("wooden_button");
		SKULL = (BlockSkull) get("skull");
		ANVIL = get("anvil");
		TRAPPED_CHEST = get("trapped_chest");
		LIGHT_WEIGHTED_PRESSURE_PLATE = get("light_weighted_pressure_plate");
		HEAVY_WEIGHTED_PRESSURE_PLATE = get("heavy_weighted_pressure_plate");
		UNPOWERED_COMPARATOR = (BlockRedstoneComparator) get("unpowered_comparator");
		POWERED_COMPARATOR = (BlockRedstoneComparator) get("powered_comparator");
		DAYLIGHT_DETECTOR = (BlockDaylightDetector) get("daylight_detector");
		DAYLIGHT_DETECTOR_INVERTED = (BlockDaylightDetector) get("daylight_detector_inverted");
		REDSTONE_BLOCK = get("redstone_block");
		QUARTZ_ORE = get("quartz_ore");
		HOPPER = (BlockHopper) get("hopper");
		QUARTZ_BLOCK = get("quartz_block");
		QUARTZ_STAIRS = get("quartz_stairs");
		ACTIVATOR_RAIL = get("activator_rail");
		DROPPER = get("dropper");
		STAINED_HARDENED_CLAY = get("stained_hardened_clay");
		BARRIER = get("barrier");
		IRON_TRAPDOOR = get("iron_trapdoor");
		HAY_BLOCK = get("hay_block");
		CARPET = get("carpet");
		HARDENED_CLAY = get("hardened_clay");
		COAL_BLOCK = get("coal_block");
		PACKED_ICE = get("packed_ice");
		ACACIA_STAIRS = get("acacia_stairs");
		DARK_OAK_STAIRS = get("dark_oak_stairs");
		SLIME = get("slime");
		DOUBLE_PLANT = (BlockTallPlant) get("double_plant");
		STAINED_GLASS = (BlockStainedGlass) get("stained_glass");
		STAINED_GLASS_PANE = (BlockStainedGlassPane) get("stained_glass_pane");
		PRISMARINE = get("prismarine");
		SEA_LANTERN = get("sea_lantern");
		STANDING_BANNER = get("standing_banner");
		WALL_BANNER = get("wall_banner");
		RED_SANDSTONE = get("red_sandstone");
		RED_SANDSTONE_STAIRS = get("red_sandstone_stairs");
		DOUBLE_STONE_SLAB2 = (BlockStepAbstract) get("double_stone_slab2");
		STONE_SLAB2 = (BlockStepAbstract) get("stone_slab2");
		END_ROD = get("end_rod");
		CHORUS_PLANT = get("chorus_plant");
		CHORUS_FLOWER = get("chorus_flower");
		PURPUR_BLOCK = get("purpur_block");
		PURPUR_PILLAR = get("purpur_pillar");
		PURPUR_STAIRS = get("purpur_stairs");
		PURPUR_DOUBLE_SLAB = (BlockStepAbstract) get("purpur_double_slab");
		PURPUR_SLAB = (BlockStepAbstract) get("purpur_slab");
		END_BRICKS = get("end_bricks");
		BEETROOT = get("beetroots");
		GRASS_PATH = get("grass_path");
		END_GATEWAY = get("end_gateway");
		dc = get("repeating_command_block");
		dd = get("chain_command_block");
		FROSTED_ICE = get("frosted_ice");
		df = get("magma");
		dg = get("nether_wart_block");
		dh = get("red_nether_brick");
		di = get("bone_block");
		dj = get("structure_void");
		dk = get("observer");
		WHITE_SHULKER_BOX = get("white_shulker_box");
		dm = get("orange_shulker_box");
		dn = get("magenta_shulker_box");
		LIGHT_BLUE_SHULKER_BOX = get("light_blue_shulker_box");
		dp = get("yellow_shulker_box");
		dq = get("lime_shulker_box");
		dr = get("pink_shulker_box");
		ds = get("gray_shulker_box");
		dt = get("silver_shulker_box");
		du = get("cyan_shulker_box");
		dv = get("purple_shulker_box");
		dw = get("blue_shulker_box");
		dx = get("brown_shulker_box");
		dy = get("green_shulker_box");
		dz = get("red_shulker_box");
		dA = get("black_shulker_box");
		dB = get("white_glazed_terracotta");
		dC = get("orange_glazed_terracotta");
		dD = get("magenta_glazed_terracotta");
		dE = get("light_blue_glazed_terracotta");
		dF = get("yellow_glazed_terracotta");
		dG = get("lime_glazed_terracotta");
		dH = get("pink_glazed_terracotta");
		dI = get("gray_glazed_terracotta");
		dJ = get("silver_glazed_terracotta");
		dK = get("cyan_glazed_terracotta");
		dL = get("purple_glazed_terracotta");
		dM = get("blue_glazed_terracotta");
		dN = get("brown_glazed_terracotta");
		dO = get("green_glazed_terracotta");
		dP = get("red_glazed_terracotta");
		dQ = get("black_glazed_terracotta");
		dR = get("concrete");
		dS = get("concrete_powder");
		STRUCTURE_BLOCK = get("structure_block");
		dU.clear();
	}
}
